# Introduction {#intro}

Welcome to class! This website is designed to accompany Mason Garrison's Data Science for Psychologists graduate course at Wake Forest University. It is both the syllabus and primary textbook. 

## Course Description
This applied course is designed for psychologists with limited programming experience. It introduces the basic tennents of data science and links them to traditional psychological approaches.  and provides a means to e 

Along the way, we will develop an understanding of R programming as well as open science practices. In general, data science focuses on exploratory analyses and description rather than on corfirmatory analyses and prediction. Through the semester we will work our way thru [Wickham and Grolemund's R for Data Science text](http://r4ds.had.co.nz/) and develop proficiency with [tidyverse](https://www.tidyverse.org/).

[This is an applied course for social scientists with little-to-no programming experience who wish to harness growing digital and computational resources. The focus of the course is on generating reproducible research through the use of programming languages and version control software. Major emphasis is placed on a pragmatic understanding of core principles of programming and packaged implementations of methods. Students will leave the course with basic computational skills implemented through many computational methods and approaches to social science; while students will not become expert programmers, they will gain the knowledge of how to adapt and expand these skills as they are presented with new questions, methods, and data.](https://cfss.uchicago.edu/)


## Broad Topics
This class cover the following broad five areas:
* Reproducibility;
* Replication;
* Robust Methods;
* Resplendent Visualizations; and
* R Programming.

## Materials


<sentence of difference between minimum, recommended, and mason. Minimum is the bare minimum that you need to function in the class. Recommended are the what I think you need in order to succeed. Mason are the levels that I am currently using. In general what I am using is beyond what any reasonable person needs. I include it primarily as a curiosity and more evidence of my "too-muchness">


The text [@funder_personality_2016] is intended to supplement the lectures. The lectures don't follow the order of chapters in the text and the text covers some material that won't be covered in the lectures, i.e., not all the information in each chapter is perfectly pertinent to the course requirements.

### Texts
#### Minimum
#### Recommended
#### Mason

### Operating System
#### Minimum
#### Recommended
#### Mason

### Hardware
#### Minimum
#### Recommended
#### Mason


### Software
#### Minimum
#### Recommended
#### Mason



```{r setup, include=FALSE}
#knitr::opts_chunk$set(cache=FALSE, dev='pdf')
#mon <- as.Date("2020-08-24")
cache=F
number_of_classes=29
number_of_weeks=15
advdate <- function(obj, adv, topic = NULL,assignment=NULL) {
 tmon <- obj + 7*(adv-1)
 ttue <- obj + 1 + 7*(adv-1)
 twed <- obj + 2 + 7*(adv-1)
 tthu <- obj + 3 + 7*(adv-1)
 tfri <- obj + 4 + 7*(adv-1)
 tmon <- format(tmon, format="%m/%d")
 ttue <- format(ttue, format="%m/%d")
 twed <- format(twed, format="%m/%d")
 tthu <- format(tthu, format="%m/%d")
 tfri <- format(tfri, format="%m/%d")
 zadv <- sprintf("%02d", adv)

 if (is.null(topic)&is.null(assignment)){
 tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri)
 } else if(!is.null(assignment)){if(assignment %in% c("Friday","friday","f","fri")){
  tmp <- paste0(tfri)
 }else if(assignment %in% c("wednesday","Wednesday","w","wed","W")){
  tmp <- paste0(twed)
 } else if(assignment %in% c("monday","Monday","m")){
  tmp <- paste0(tmon)
 }
 }
 else{ 
   tmp <- paste("Week ",zadv,sep='',", ", tmon," - ",tfri, " : ", topic[adv])}
 return(tmp)
}

####
#devtools::install_github("crsh/citr")
library(tidyverse)
library(citr)
library(RefManageR)



topic=c( )
```
