# Activity: UN voting {#ae01}

```{r act_voting-setup, include = FALSE}
source("common.R")

# install.packages("devtools")

if (!require("tweetrmd")) devtools::install_github("gadenbuie/tweetrmd")
library(tweetrmd) # ... embedding tweets
library(vembedr)
ds4p_urls <- read.csv("./admin/csv/ds4p_urls.csv")
```


<!--
You can do either activity. The choice is yours.

* Activities
  * [UN Voting][ae01a_unvotes]
  * [Covid Data][ae01b_covid]
-->


## UN Voting

```{r embed-unvoting-activity-slides, echo=FALSE}
slide_url(ds4p_urls, "d01_welcome", "#53") %>%
  include_url(height = "400px")
```

You can find the materials for the UN activity [here][ae01a_unvotes].
The compiled version should look something like the following... This activity is designed to get you comfortable with R Markdown and Git/GitHub. 

```{r embed-unvotes-compiled-example, echo=FALSE}
"https://datascience4psych.github.io/ae01a_unvotes/unvotes.html" %>%
  include_url(height = "400px")
```

<!--
## COVID Data

```{r embed-covid-activity-slides, echo=FALSE}
slide_url(ds4p_urls, "d01_welcome", "#54") %>%
  include_url(height = "400px")
```

You can find the materials for the Covid version of this activity [here][ae01b_covid].
The compiled version should look something like the following...

```{r embed-covid-activity-example, echo=FALSE}
"https://datascience4psych.github.io/ae01b_covid/covid.html" %>%
  include_url(height = "400px")
```
-->

## Learning Outcomes

```{r embed-learning, echo=FALSE}
slide_url(ds4p_urls, "d01_welcome", "#56") %>%
  include_url(height = "400px")
```



```{r courselinks, child="admin/md/courselinks.md"}
```
