```{r act_another_hotel-setup, include = FALSE}
source("common.R")
ds4p_funyoutube <- read.csv("admin/csv/ds4p_funyoutube.csv", sep = "")
ds4p_urls <- read.csv("./admin/csv/ds4p_urls.csv")
```

### (An) Another Hotels Activity

```{r embed-hotels-activity-slides, echo=FALSE}
slide_url(ds4p_urls, "d11_types", "#50") %>%
  include_url(height = "400px")
```

You can find the materials for the Hotels activity [here](https://github.com/DataScience4Psych/ae-05-hotels-datatypes). The compiled version should look something like the following...

```{r embed-hotels-activity-example, echo=FALSE}
"https://datascience4psych.github.io/ae-05-hotels-datatypes/hotels-forcats.html" %>%
  include_url(height = "400px")
```

## Working with Dates

```{r embed-working-with-dates-video, echo=FALSE}
# Working with Dates
"https://www.youtube.com/watch?v=R6cEDlzCBfQ" %>%
  embed_url() %>%
  use_align("center")
```

```{r embed-working-with-dates-slides, echo=FALSE}
slide_url(ds4p_urls, "d11_types", "#52") %>%
  include_url(height = "400px")
```

```{r links, child="admin/md/courselinks.md"}
```
