```{r diving-setup, include = FALSE}
source("common.R")
ds4p_funyoutube <- read.csv("metadata/ds4p_funyoutube.csv", sep = "")
ds4p_urls <- read.csv("./metadata/ds4p_urls.csv")
```

# LEC: Deeper Diving into ggplot2

```{r diving-include-video-intro, echo=FALSE}
# 503
"https://www.youtube.com/watch?v=xLBMJMkwc-U" %>%
  embed_url() %>%
  use_align("center")
```

You can follow along with the slides [here][d13b_moreggplot] if you would like to open them full-screen.

```{r diving-include-slides-intro, echo=FALSE}
slide_url(ds4p_urls, "d13b_moreggplot") %>%
  include_url(height = "400px")
```

## What are the components of a plot?

```{r diving-include-video-components, echo=FALSE}
# 504
"https://www.youtube.com/watch?v=Eg6hH-1qX5I" %>%
  embed_url() %>%
  use_align("center")
```

```{r diving-include-slides-components, echo=FALSE}
slide_url(ds4p_urls, "d13b_moreggplot", "#17") %>%
  include_url(height = "400px")
```

## Stats, Geoms, and Positions

```{r diving-include-video-stats-geoms, echo=FALSE}
# Stats, Geoms, and Positions
"https://www.youtube.com/watch?v=SklAl8uyuv4" %>%
  embed_url() %>%
  use_align("center")
```

```{r diving-include-slides-stats-geoms, echo=FALSE}
slide_url(ds4p_urls, "d13b_moreggplot", "#29") %>%
  include_url(height = "400px")
```

### Jitter to the rescue

```{r diving-include-tweet-jitter, echo=FALSE}
try_include_tweet("https://twitter.com/mijkenijk/status/1365913365755822089")
```

## Scales and Coordinates

```{r diving-include-video-scales, echo=FALSE}
# Scales and Coordinates
"https://www.youtube.com/watch?v=vn8RToV1cc4" %>%
  embed_url() %>%
  use_align("center")
```

```{r diving-include-slides-scales, echo=FALSE}
slide_url(ds4p_urls, "d13b_moreggplot", "#41") %>%
  include_url(height = "400px")
```

## How this all works with Minard

```{r diving-include-video-minard, echo=FALSE}
# Minnard
"https://www.youtube.com/watch?v=9nWaGrEMA54" %>%
  embed_url() %>%
  use_align("center")
```

```{r diving-include-slides, echo=FALSE}
slide_url(ds4p_urls, "d13b_moreggplot", "#59") %>%
  include_url(height = "400px")
```

```{r courselinks, child="includes/courselinks.md"}
```
