# LEC: Scientific studies and confounding

```{r confounds-setup, include = FALSE, echo = FALSE, message=FALSE, warning=FALSE}
source("common.R")

library(tidyverse)
library(knitr)
library(DT)
```


```{r confounds-include-tweet-intro, echo=FALSE}
try_include_tweet("https://twitter.com/JkayFlake/status/1475533542302093315")
```

You can follow along with the slides [here][d14_confound] if you would like to open them full-screen.

## Scientific studies

```{r confounds-include-video-studies, echo=FALSE,eval = knitr::is_latex_output()}
embed_youtube_alt("OHfk4dbzNBc")
```
```{r confounds-include-video-studies-html, echo=FALSE,eval = knitr::is_html_output()}
"https://www.youtube.com/watch?v=OHfk4dbzNBc" %>%
  embed_url() %>%
  use_align("center")
```

```{r confounds-include-slides-studies, echo=FALSE}
slide_url(ds4p_urls, "d14_confound") %>%
  include_url(height = "400px")
```

## Climate Change: A Conditional Probability Case Study

```{r confounds-include-video-climate, echo=FALSE,eval = knitr::is_latex_output()}
embed_youtube_alt("Fv-yucms7lQ")
```
```{r confounds-include-video-climate-html, echo=FALSE,eval = knitr::is_html_output()}
"https://www.youtube.com/watch?v=Fv-yucms7lQ" %>%
  embed_url() %>%
  use_align("center")
```

```{r confounds-include-slides-climate, echo=FALSE}
slide_url(ds4p_urls, "d14_confound", "#22") %>%
  include_url(height = "400px")
```

## Introducing Simpson's Paradox with a case study

```{r confounds-include-video-simpson-intro, echo=FALSE,eval = knitr::is_latex_output()}
embed_youtube_alt("My68gFE_usU")
```
```{r confounds-include-video-simpson-intro-html, echo=FALSE,eval = knitr::is_html_output()}
"https://www.youtube.com/watch?v=My68gFE_usU" %>%
  embed_url() %>%
  use_align("center")
```

```{r confounds-include-slides-simpson-intro, echo=FALSE}
slide_url(ds4p_urls, "d14_confound", "#42") %>%
  include_url(height = "400px")
```

## Revisiting Simpson's Paradox

```{r confounds-include-video-simpson-revisit, echo=FALSE,eval = knitr::is_latex_output()}
embed_youtube_alt("vVq_G-a6K30")
```
```{r confounds-include-video-simpson-revisit-html, echo=FALSE,eval = knitr::is_html_output()}
"https://www.youtube.com/watch?v=vVq_G-a6K30" %>%
  embed_url() %>%
  use_align("center")
```

```{r confounds-include-slides-simpson, echo=FALSE}
slide_url(ds4p_urls, "d14_confound", "#62") %>%
  include_url(height = "400px")
```


```{r courselinks, child="includes/courselinks.md"}
```
