# Lecture: Automation
```{r automation-setup, include = FALSE}
source("common.R")
ds4p_funyoutube <- read.csv("admin/csv/ds4p_funyoutube.csv", sep = "")
ds4p_urls <- read.csv("./admin/csv/ds4p_urls.csv")
```


You can follow along with the slides [here][d17_functions] if you would like to open them full-screen.

```{r automation-include-video, echo=FALSE,eval = knitr::is_latex_output()}
embed_youtube_alt("BZrm_tlvCq4")
```
```{r automation-include-video, echo=FALSE,eval = knitr::is_html_output()}
"https://www.youtube.com/watch?v=BZrm_tlvCq4" %>%
  embed_url() %>%
  use_align("center")
```

```{r automation-include-slides, echo=FALSE}
slide_url(ds4p_urls, "d17_functions", "#42") %>%
  include_url(height = "400px")
```

## Code Along pt 3

```{r automation-include-slides, echo=FALSE}
slide_url(ds4p_urls, "d17_functions", "#54") %>%
  include_url(height = "400px")
```

You can find the materials for this activity [here](https://github.com/DataScience4Psych/ae-09-uoeart-functions).

## Math to Coding

```{r automation-include-tweet, echo=FALSE}
try_include_tweet("https://twitter.com/FreyaHolmer/status/1436696408506212353")
```

```{r links, child="admin/md/courselinks.md"}
```
