# (PART) Module 14 {-}

# Welcome to Large Language Models in Data Science

```{r include = FALSE}
source("common.R")

ds4p_funyoutube <- read.csv("admin/csv/ds4p_funyoutube.csv", sep = "")
ds4p_urls <- read.csv("./admin/csv/ds4p_urls.csv")

# install.packages("devtools")

if (!require("tweetrmd"))  devtools::install_github("gadenbuie/tweetrmd")
library(tweetrmd) #... embedding tweets
library(vembedr)  #... embedding youtube videos
library(knitr)
library(tidyverse)
```
This module introduces Large Language Models (LLMs) and their applications in data science. We'll explore basic concepts, use cases, ethical considerations, and hands-on applications of LLMs. Eventually, there will be video lectures. Once those videos exist, please watch the videos and work your way through the notes. **The videos will eventually start on the next page.**  You will eventually be able to find the video playlist for this module [here][pl_llm]. The slides used to make the videos in this module will be able to be found in the [slides repo][course_slides]. 

This module is in active development, as part of an AI teaching workshop sponsored by the Wake Forest University's Center for Teaching.

## Module Materials

* Slides from Lectures:
  * [Intro to LLMs][d31_llm], 
  * [LLMs in Data Science][d32_llmapplications], 
  * [LLM Ethics][d33_llmethics]
* Suggested Readings
  * All subchapters of this module, including
    * ...
  * R4DS
    * [TBD](https://r4ds.had.co.nz/), including
      * [TBD]
      * [TBD]
   * GPT-3 Paper, Foundation Models
* Activities
  * Exploring LLM Capabilities with OpenAI's API [TBD]
* Lab
  * [TBD](#labTBD)

## Estimated Video Length

<!--https://ytplaylist-len.herokuapp.com/ -->

No of videos : TBD

Average length of video : TBD

Total length of playlist : TBD



