# Lecture: What are Large Language Models?

```{r include = FALSE}
source("common.R")

ds4p_funyoutube <- read.csv("admin/csv/ds4p_funyoutube.csv", sep = "")
ds4p_urls <- read.csv("./admin/csv/ds4p_urls.csv")

# install.packages("devtools")

if (!require("tweetrmd"))  devtools::install_github("gadenbuie/tweetrmd")
library(tweetrmd) #... embedding tweets
library(vembedr)  #... embedding youtube videos
library(knitr)
library(tidyverse)
```


You can follow along with the slides [here][d31_llm] if they do not appear below.

```{r, echo=FALSE}
# Designing effective visualizations
#"https://www.youtube.com/watch?v=H9NHHs5VKZc" %>%
#  embed_url() %>%
#  use_align("center")
#

video_url=sample_no_surprises(ds4p_funyoutube$funyoutube)
 embed_url(video_url) %>%
  use_align("center")

```

```{r, echo=FALSE}
slide_url(ds4p_urls, "d31_llm") %>%
  include_url(height = "400px")
```

## Basic Concepts of LLMs
[Content on transformer architecture, training process, etc.]

## Evolution of LLMs

[Content on progression from early models to current state-of-the-art]


# Lecture: Applications of Large Language Models in Data Science

You can follow along with the slides [here][d32_llmapplications] if they do not appear below.

```{r, echo=FALSE}
# Designing effective visualizations
#"https://www.youtube.com/watch?v=H9NHHs5VKZc" %>%
#  embed_url() %>%
#  use_align("center")
#

video_url=sample_no_surprises(ds4p_funyoutube$funyoutube)
 embed_url(video_url) %>%
  use_align("center")

```

```{r, echo=FALSE}
slide_url(ds4p_urls, "d32_llmapplications") %>%
  include_url(height = "400px")
```

## Use Cases in Data Science

[Content on text generation, summarization, classification, etc.]
