# Lecture: Ethical Considerations of LLMs

```{r include = FALSE}
source("common.R")

ds4p_funyoutube <- read.csv("admin/csv/ds4p_funyoutube.csv", sep = "")
ds4p_urls <- read.csv("./admin/csv/ds4p_urls.csv")

# install.packages("devtools")

if (!require("tweetrmd"))  devtools::install_github("gadenbuie/tweetrmd")
library(tweetrmd) #... embedding tweets
library(vembedr)  #... embedding youtube videos
library(knitr)
library(tidyverse)
```


You can follow along with the slides [here][d31_llm] if they do not appear below.

```{r, echo=FALSE}
# Designing effective visualizations
#"https://www.youtube.com/watch?v=H9NHHs5VKZc" %>%
#  embed_url() %>%
#  use_align("center")
#

video_url=sample_no_surprises(ds4p_funyoutube$funyoutube)
 embed_url(video_url) %>%
  use_align("center")

```

```{r, echo=FALSE}
slide_url(ds4p_urls, "d33_llmethics") %>%
  include_url(height = "400px")
```
## Bias and Fairness

[Content on potential biases in LLMs and mitigation strategies]

## Privacy and Security
[Content on data privacy concerns and best practices]

## Environmental Impact
[Content on computational resources and environmental implications]
