# (PART) Other Coolness {-}

```{r include = FALSE}
source("common.R")

# install.packages("devtools")

if (!require("tweetrmd"))  devtools::install_github("gadenbuie/tweetrmd")
library(tweetrmd) #... embedding tweets
library(vembedr)  #... embeding youtube videos
library(knitr)
```

# Good Resources

https://psychnerdjae.github.io/into-the-tidyverse/


# Media without a home yet

## How computer memory works!

```{r, echo=FALSE}
# How computer memory works - Kanawat Senanan
embed_url("https://www.youtube.com/watch?v=p3q5zWCw8J4") %>%
  use_align("center")
```


## Quantum Computers Explained!

```{r, echo=FALSE}
# Quantum Computers Explained
embed_url("https://www.youtube.com/watch?v=JhHMJCUmq28") %>%
  use_align("center")
```


## The Rise of the Machines – Why Automation is Different this Time

```{r, echo=FALSE}
# Quantum Computers Explained
embed_url("https://www.youtube.com/watch?v=WSKi8HfcxEk") %>%
  use_align("center")
```

## Who Would Be King of America if George Washington had been made a monarch?

```{r, echo=FALSE}
# Who Would Be King of America if George Washington had been made a monarch?
embed_url("https://www.youtube.com/watch?v=ZxnBveop5no") %>%
  use_align("center")
```

## Emergence – How Stupid Things Become Smart Together

```{r, echo=FALSE}
# Emergence – How Stupid Things Become Smart Together

embed_url("https://www.youtube.com/watch?v=16W7c0mb-rE") %>%
  use_align("center")
```


## The Birthday Paradox


```{r, echo=FALSE}
# The Birthday Paradox

embed_url("https://www.youtube.com/watch?v=ofTb57aZHZs") %>%
  use_align("center")
```
