# Configuration file for typos spellchecker
# See: https://github.com/crate-ci/typos

[default]
extend-ignore-re = [
  # Ignore R code chunks
  "```\\{r.*?```",
  # Ignore inline R code
  "`r [^`]+`",
  # Ignore URLs
  "https?://[^\\s]+",
  # Ignore email addresses
  "[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\\.[a-zA-Z]{2,}",
]

[default.extend-words]
# R and RStudio specific terms
Rmd = "Rmd"
rmarkdown = "rmarkdown"
knitr = "knitr"
ggplot = "ggplot"
dplyr = "dplyr"
tidyverse = "tidyverse"
tidyr = "tidyr"
tibble = "tibble"
readr = "readr"
purrr = "purrr"
stringr = "stringr"
forcats = "forcats"
lubridate = "lubridate"
bookdown = "bookdown"
RStudio = "RStudio"
Rstudio = "RStudio"
CRAN = "CRAN"
Shiny = "Shiny"

# Data Science terms
API = "API"
APIs = "APIs"
DataFrame = "DataFrame"
repo = "repo"
repos = "repos"
csv = "csv"
JSON = "JSON"
YAML = "YAML"
url = "url"
urls = "urls"
workflow = "workflow"
workflows = "workflows"

# Psychology and academic terms
neuroscience = "neuroscience"
Psych = "Psych"
visualizations = "visualizations"
behavioural = "behavioural"
extraversion = "extraversion"  # Alternative spelling of extroversion used in psychology

# Project specific terms
DataScience4Psych = "DataScience4Psych"
Garrison = "Garrison"
Wickham = "Wickham"
Grolemund = "Grolemund"
Hadley = "Hadley"
Garett = "Garett"

# Common code/tech terms that might be flagged
github = "github"
Github = "Github"
GitHub = "GitHub"
localhost = "localhost"
config = "config"
utils = "utils"
param = "param"
params = "params"
async = "async"
backend = "backend"
frontend = "frontend"

# File extensions and formats
html = "html"
pdf = "pdf"
md = "md"
png = "png"
jpg = "jpg"
svg = "svg"

[files]
extend-exclude = [
  "*.png",
  "*.jpg",
  "*.jpeg",
  "*.gif",
  "*.svg",
  "*.pdf",
  "*.csv",
  "*.rds",
  "*.RData",
  "*.html",
  "*.HTML",
  "docs/*",
  "*.min.js",
  "*.min.css",
  "packrat/*",
  "renv/*",
  "node_modules/*",
  "_book/*",
  "_bookdown_files/*",
  "*.bib",
  "packages.bib",
  "book.bib",
  "parameterized/*.HTML",
  "parameterized/*.html",
]
