#libraries
install.packages("devtools")
install.packages(c("tidyverse", "rmarkdown"))
install.packages(c("bookdown", "discord"))
install.packages("vembedr")
devtools::install_github("gadenbuie/tweetrmd")
install.packages("datasauRus")
install.packages("DT")
install.packages("car")
install.packages("latticeExtra")
install.packages("manipulateWidget")
install.packages("shiny")
install.packages("rgl")
devtools::install_github('gmonette/spida2')
install.packages("p3d", repos = "http://R-Forge.R-project.org")

install.packages("tufte")
devtools::install_github("rstudio-education/dsbox")

install.packages("rafalib")
install.packages("rgl")
if (!requireNamespace("BiocManager", quietly = TRUE)) install.packages("BiocManager")
BiocManager::install("Biobase")
BiocManager::install("SpikeInSubset")
install.packages("pacman")
devtools::install_github("hadley/emo")
install.packages("openintro")
install.packages("ggridges")
