```{r include = FALSE}
source("common.R")
ds4p_funyoutube <- read.csv("admin/csv/ds4p_funyoutube.csv", sep="")
ds4p_urls <- read.csv("./admin/csv/ds4p_urls.csv")
```

```{r links, child="admin/md/courselinks.md"}
```

# ODD: Legacy Data Types {-}

This optional deep dive contains examples of legacy data structures and formatting. 
Why? I have found it very helpful to remind myself that whatever problem I'm grappling with in R could be so much worse. 

## Punchcards

### The Keypunch Machine (IBM)
```{r, echo=FALSE}
# 1960s PUNCHED CARD DATA PROCESSING / KEY PUNCH MACHINE IBM 029 COMPUTER "THE KEY PUNCH" 62464
video_url="https://www.youtube.com/watch?v=DQ4f1MItR9Y"
embed_url(video_url) %>%
  use_align("center")
```

### Punch Card Programming - Computerphile
```{r, echo=FALSE}
# 1960s PUNCHED CARD DATA PROCESSING / KEY PUNCH MACHINE IBM 029 COMPUTER "THE KEY PUNCH" 62464
video_url="https://www.youtube.com/watch?v=KG2M4ttzBnY"
embed_url(video_url) %>%
  use_align("center")
```


## Magnetic Type

## Paper!
